name: cxx11_win

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: macos-cxx11
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir _build && cd _build
        cmake ../ -DENABLE_STDCXX_SYNC=ON -DENABLE_ENCRYPTION=OFF -DENABLE_UNITTESTS=ON
    - name: build
      run: cd _build && cmake --build ./
    - name: test
      run: cd _build && ctest --extra-verbose
